name: Run Cypress Tests with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file for Docker Compose
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.ci
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.ci
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env.ci
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.ci
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.ci

      - name: Build and start containers
        run: docker-compose --env-file .env.ci -f docker-compose.ci.yaml up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for server and client to be ready..."
          sleep 20
          docker-compose --env-file .env.ci -f docker-compose.ci.yaml ps

      - name: Run Cypress tests
        run: docker-compose --env-file .env.ci -f docker-compose.ci.yaml run --rm --entrypoint "" client npx cypress run --config-file cypress.config.ts


      - name: Stop containers
        if: always()
        run: docker-compose --env-file .env.ci -f docker-compose.ci.yaml down