name: Run Cypress Tests with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file for Docker Compose
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.ci
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.ci
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env.ci
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.ci
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.ci

      - name: Build and start server & database containers
        run: docker compose --env-file .env.ci -f docker-compose.ci.yaml up -d --build server db

      - name: Run Cypress tests
        run: |
          docker compose --env-file .env.ci -f docker-compose.ci.yaml --project-name e2e exec -T client sh -c "\
            npx cypress run --headless --browser chrome --no-sandbox \
          "

      - name: Stop containers
        if: always()
        run: docker compose --env-file .env.ci -f docker-compose.ci.yaml down